export type UserRole = 'Admin' | 'Teacher' | 'CR' | 'Student';

export type RiskStatus = 'On Track' | 'Needs Attention' | 'At Risk';

export type AttendanceStatus = 'Present' | 'Absent' | 'Late' | 'Excused';

export type SessionStatus = 'Upcoming' | 'In Progress' | 'Completed' | 'Cancelled';

export type SessionMode = 'Offline' | 'Online' | 'Hybrid';

export type PriorityLevel = 'Low' | 'Medium' | 'High' | 'Urgent';

export type FollowUpStatus = 'Pending' | 'In Progress' | 'Completed' | 'Cancelled';

export type FollowUpIssueType =
  | 'Low Attendance'
  | 'Assignment'
  | 'Performance'
  | 'Participation'
  | 'Session Issue'
  | 'Student Request'
  | 'Faculty Instruction'
  | 'Other';

export type TaskCategory =
  | 'Attendance'
  | 'Session'
  | 'Student Support'
  | 'Communication'
  | 'Faculty Coordination'
  | 'Reporting'
  | 'General';

export type TaskStatus = 'Pending' | 'In Progress' | 'Completed';

export interface StudentSkillScores {
  communication: number; // 0 - 100
  grammar: number;
  vocabulary: number;
  pronunciation: number;
  participation: number;
  assignments: number;
  assessments: number;
}

export interface StudentAssignment {
  id: string;
  title: string;
  dueDate: string;
  status: 'Submitted' | 'Graded' | 'Pending' | 'Late';
  score?: number | null;
  maxScore: number;
}

export interface CRRemark {
  id: string;
  date: string;
  author: string;
  text: string;
}

export interface HistoricalScore {
  date: string;
  overallScore: number;
  communication: number;
  grammar: number;
  vocabulary: number;
}

export interface Student {
  id: string;
  name: string;
  phone: string;
  email: string;
  batch: string;
  group?: string;
  discussionGroup?: string;
  rollNo?: string;
  joiningDate: string;
  currentLevel: string;
  initialRemarks: string;
  avatar?: string;
  bio?: string;
  headline?: string;
  publicLinks?: UserSocialLinks;
  lastActivity: string;
  skills: StudentSkillScores;
  previousOverallScore: number; // to show improvement/trend
  assignments: StudentAssignment[];
  crRemarks: CRRemark[];
  historicalScores: HistoricalScore[];
  isArchived?: boolean;
}

export interface AttendanceRecord {
  sessionId: string;
  studentId: string;
  status: AttendanceStatus;
  remarks?: string;
  timestamp: string;
}

export interface Session {
  id: string;
  topic: string;
  date: string; // YYYY-MM-DD
  startTime: string; // e.g. "09:30 AM"
  endTime: string;   // e.g. "11:00 AM"
  faculty: string;
  batch: string;
  mode: SessionMode;
  location: string;
  status: SessionStatus;
  notes?: string;
  sessionType?: string;
}

export interface FollowUp {
  id: string;
  studentId: string;
  studentName: string;
  issueType: FollowUpIssueType;
  priority: PriorityLevel;
  dateIdentified: string;
  actionRequired: string;
  assignedTo: string;
  deadline: string;
  status: FollowUpStatus;
  remarks: string;
  isAutoGenerated?: boolean;
}

export interface CRTask {
  id: string;
  task: string;
  category: TaskCategory;
  priority: PriorityLevel;
  dueDate: string;
  status: TaskStatus;
  notes?: string;
}

export interface AppSettings {
  onTrackThreshold: number;       // default 85%
  needsAttentionThreshold: number;// default 70%
  atRiskThreshold: number;        // default 70%
  lateAttendanceWeight: number;   // default 0.5 or 1.0
  scoringScale: '100' | '10';
  batches: string[];
  groups?: string[];
  facultyList: string[];
  sessionTypes: string[];
  notifications: {
    lowAttendanceAlerts: boolean;
    followUpReminders: boolean;
    sessionReminders: boolean;
    taskReminders: boolean;
  };
}

export interface StudentCalculatedStats {
  student: Student;
  totalApplicableSessions: number;
  presentCount: number;
  absentCount: number;
  lateCount: number;
  excusedCount: number;
  attendedSessions: number;
  missedSessions: number;
  attendancePercentage: number;
  status: RiskStatus;
  overallScore: number;
  scoreImprovement: number;
}

export interface StudentRequest {
  id: string;
  studentId: string;
  studentName: string;
  type:
    | 'Leave / Absence Excuse'
    | 'Doubt in Lecture'
    | 'Assignment Help'
    | 'CR Notes Request'
    | 'Doubt / Query'
    | 'Assignment Extension'
    | 'General Feedback';
  subject: string;
  message: string;
  date: string;
  status: 'Pending' | 'Approved' | 'Resolved';
  teacherOrCrResponse?: string;
  resolvedDate?: string;
}

export interface UserSocialLinks {
  github?: string;
  linkedin?: string;
  portfolio?: string;
  twitter?: string;
  leetcode?: string;
  imageLink?: string;
}

export interface GoogleUser {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: UserRole;
  isGoogleAuthenticated: boolean;
  studentId?: string;
  mustChangePassword?: boolean;
  bio?: string;
  headline?: string;
  publicLinks?: UserSocialLinks;
}

export interface ActivityLog {
  id: string;
  timestamp: string;
  actorName: string;
  actorRole: string;
  action: string;
  details: string;
  category: 'attendance' | 'academic' | 'system' | 'communication';
  targetId?: string | null;
  targetName?: string | null;
}
