import mongoose from 'mongoose';

const FollowUpSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true },
  studentId: { type: String, required: true, index: true },
  studentName: { type: String, required: true },
  issueType: { 
    type: String, 
    enum: ['Low Attendance', 'Assignment', 'Performance', 'Participation', 'Session Issue', 'Student Request', 'Faculty Instruction', 'Other'], 
    required: true 
  },
  priority: { type: String, enum: ['Low', 'Medium', 'High', 'Urgent'], default: 'Medium' },
  dateIdentified: { type: String, default: () => new Date().toISOString().split('T')[0] },
  actionRequired: { type: String, required: true },
  assignedTo: { type: String, default: 'Aarav (Lead CR)' },
  deadline: { type: String, required: true },
  status: { type: String, enum: ['Pending', 'In Progress', 'Completed', 'Cancelled'], default: 'Pending', index: true },
  remarks: { type: String, default: '' },
  isAutoGenerated: { type: Boolean, default: false }
}, {
  timestamps: true
});

export const FollowUp = mongoose.models.FollowUp || mongoose.model('FollowUp', FollowUpSchema);
